stage_detection: false
stage_classification: true

general:
  save_dir: "baclog_n1"
  project_name: "bacteria_n1"

trainer:
  devices: 1
  accelerator: "auto"
  precision: "16-mixed"
  log_every_n_steps: 10

training:
  seed: 666
  mode: "max"
  tuning_epochs_detection: 5
  tuning_epochs_classification: 5
  additional_epochs_detection: 5
  additional_epochs_classification: 5
  cross_validation: false
  num_folds: 3

optimizer:
  class_name: "torch.optim.AdamW"
  params:
    lr: 1e-4
    weight_decay: 0.001

scheduler:
  class_name: "torch.optim.lr_scheduler.ReduceLROnPlateau"
  step: "epoch"
  monitor: "val_acc"
  params:
    mode: "max"
    factor: 0.1
    patience: 3

model:
  backbone:
    class_name: "torchvision.models.resnet50"
    params:
      weights: "ResNet50_Weights.IMAGENET1K_V1"

data:
  detection_csv: "C:/Users/Natthacha/Downloads/bts finnder/Dataset/Fa/stage1_train.csv"
  classification_csv: "C:/Users/Natthacha/Downloads/bts finnder/Dataset/Fa/stage2_train.csv"
  test_csv: "C:/Users/Natthacha/Downloads/bts finnder/Dataset/Fa/test.csv"
  folder_path: "C:/Users/Natthacha/Downloads/bts finnder/Dataset/Fa"
  num_workers: 0
  batch_size: 4
  label_col: "label"
  valid_split: 0.2

augmentation:
  train:
    augs:
      - class_name: "albumentations.Resize"
        params:
          height: 400
          width: 400
          p: 1.0
      - class_name: "bacteria_lib.transforms.ToGray3"
        params:
          p: 1.0
      - class_name: "albumentations.HorizontalFlip"
        params:
          p: 0.5
      - class_name: "albumentations.RandomBrightnessContrast"
        params:
          p: 0.5
      - class_name: "albumentations.Normalize"
        params: {}
      - class_name: "albumentations.pytorch.transforms.ToTensorV2"
        params:
          p: 1.0
  valid:
    augs:
      - class_name: "albumentations.Resize"
        params:
          height: 400
          width: 400
          p: 1.0
      - class_name: "bacteria_lib.transforms.ToGray3"
        params:
          p: 1.0
      - class_name: "albumentations.Normalize"
        params: {}
      - class_name: "albumentations.pytorch.transforms.ToTensorV2"
        params:
          p: 1.0

optuna:
  use_optuna: true
  n_trials: 5
  params:
    lr:
      min: 1e-5
      max: 1e-3
      type: "loguniform"
    batch_size:
      values: [4, 8]
      type: "categorical"
    gradient_clip_val:
      min: 0.0
      max: 0.3
      type: "float"
